# Welcome to the config.yml!
# Please checkout the documentation for info on how to configure this


# Required config info
Token:
Prefix:
Owner Id:

# Moderation
Mod Log Channel ID: 00000000000000000000
Moderator Role ID: 00000000000000000000
Ban Command: true
Temp Ban Command: true
Kick Command: true
Warn Command: true
Mute Command: true

# Utility
Welcome Channel ID: 00000000000000000000
Ping Command: true
Days Command: true
Messages Command: true
Invites Command: true

# Fun
Youtube Updates Channel ID: 00000000000000000000
Twitch Updates Channel ID: 00000000000000000000
Twitter Updates Channel ID: 00000000000000000000
Meme Command: true
Pet Command: true

